from __future__ import annotations
# -*- coding: utf-8 -*-
# code generated by Prisma. DO NOT EDIT.
# fmt: off
# -- template metadata.py.jinja --


PRISMA_MODELS: set[str] = {
    'Application_logs',
    'Document_store',
}

RELATIONAL_FIELD_MAPPINGS: dict[str, dict[str, str]] = {
    'Application_logs': {
    },
    'Document_store': {
    },
}

# fmt: on